"""
Auto-generated catalog of Ontario generators currently dispatching into
the IESO market. Source: IESO Generator Output and Capability XML report
(`PUB_GenOutputCapability.xml`), pulled live from reports-public.ieso.ca.

Each entry is a generating station (unit-level rows like BRUCEA-G1..G8
are rolled up into the parent station). Nameplate MW is the max of the
~17 hourly Output/Capability readings in the file — so it's an
operationally-observed maximum, not the dispatch-rated nameplate, but
within a few percent for thermal / nuclear.

Fuel type uses IESO's own labels (NUCLEAR, GAS, HYDRO, WIND, SOLAR, …).

DO NOT EDIT BY HAND - re-run `python -m
backend.scripts.ingest_ieso_generators`.

Used by:
  - agents/site_generation.py (optional: shown to Claude alongside the
    OSM substation list so candidate proposals know where existing
    generation sits)
"""

IESO_GENERATORS: list[dict] = [
    {"station": "BRUCEB", "fuel": "NUCLEAR", "unit_count": 4, "nameplate_mw": 3290.0},
    {"station": "DARLINGTON", "fuel": "NUCLEAR", "unit_count": 4, "nameplate_mw": 1818.0},
    {"station": "BRUCEA", "fuel": "NUCLEAR", "unit_count": 4, "nameplate_mw": 1656.0},
    {"station": "PICKERINGB", "fuel": "NUCLEAR", "unit_count": 4, "nameplate_mw": 1555.0},
    {"station": "BECK2", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 1402.0},
    {"station": "LENNOX", "fuel": "GAS", "unit_count": 4, "nameplate_mw": 1050.0},
    {"station": "NAPANEE", "fuel": "GAS", "unit_count": 3, "nameplate_mw": 978.0},
    {"station": "SAUNDERS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 849.0},
    {"station": "PORTLANDS", "fuel": "GAS", "unit_count": 3, "nameplate_mw": 646.0},
    {"station": "BRIGHTON BEACH", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 642.0},
    {"station": "STCLAIRCGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 614.0},
    {"station": "TASARNIA", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 505.0},
    {"station": "YORKCGS", "fuel": "GAS", "unit_count": 2, "nameplate_mw": 466.0},
    {"station": "BECK1", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 453.0},
    {"station": "DESJOACHIMS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 429.0},
    {"station": "SITHE GOREWAY-G15", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 362.0},
    {"station": "CANYON", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 341.0},
    {"station": "GREENFIELD ENERGY CENTRE-G4", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 330.0},
    {"station": "HAGERSVILLE BESS", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 327.0},
    {"station": "THOROLDCGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 303.0},
    {"station": "NAPANEE BESS", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 278.0},
    {"station": "LOWERNOTCH", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 274.0},
    {"station": "K2WIND", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 270.0},
    {"station": "RAILBEDWF-LT.AG_SR", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 270.0},
    {"station": "SMOKY 2", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 266.0},
    {"station": "ONEIDA ENERGY STORAGE", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 250.0},
    {"station": "HALTONHILLS-LT.G2", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 230.0},
    {"station": "WEST LINCOLN NRWF", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 230.0},
    {"station": "SITHE GOREWAY-G11", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 212.0},
    {"station": "SITHE GOREWAY-G12", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 212.0},
    {"station": "SITHE GOREWAY-G13", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 212.0},
    {"station": "WELLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 209.0},
    {"station": "HYDROGEN READY POWER PLANT (HRPP)", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 206.0},
    {"station": "HOLDEN", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 199.0},
    {"station": "HALTONHILLS-LT.G1", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 198.0},
    {"station": "GREENFIELD SOUTH-G1", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 192.0},
    {"station": "HALTONHILLS-LT.G3", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 190.0},
    {"station": "PRINCEFARM", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 189.0},
    {"station": "CARDINAL", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 184.0},
    {"station": "HENVEY SOUTH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 183.0},
    {"station": "AMARANTH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 182.0},
    {"station": "UNDERWOOD", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 182.0},
    {"station": "ARMOW", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 180.0},
    {"station": "GREENFIELD ENERGY CENTRE-G2", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 175.0},
    {"station": "GREENFIELD ENERGY CENTRE-G3", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 175.0},
    {"station": "MTNCHUTE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 173.0},
    {"station": "WOLFE ISLAND", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 171.0},
    {"station": "CHATSFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 168.0},
    {"station": "COMBER", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 166.0},
    {"station": "STEWARTVLE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 160.0},
    {"station": "CHENAUX", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 158.0},
    {"station": "HARMON", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 156.0},
    {"station": "OTTERRAPIDS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 152.0},
    {"station": "GRANDWF", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 149.0},
    {"station": "JERICHO", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 149.0},
    {"station": "DECEWFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 148.0},
    {"station": "PINEPORTAGE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 146.0},
    {"station": "WESTWINDSOR", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 143.0},
    {"station": "GREENFIELD SOUTH-G2", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 133.0},
    {"station": "YORK BESS", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 132.0},
    {"station": "LAKESUPERIOR", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 125.0},
    {"station": "NPIROQFALLS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 125.0},
    {"station": "SUMMERHAVEN", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 124.0},
    {"station": "DESTEC", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 120.0},
    {"station": "HENVEY NORTH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 117.0},
    {"station": "BECK2 PGS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 116.0},
    {"station": "SANDUSK-LT.AG_T1", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 104.0},
    {"station": "GOSHEN", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 102.0},
    {"station": "PORTALMA-T1", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 101.0},
    {"station": "PORTALMA-T3", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 101.0},
    {"station": "BELLE RIVER", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 100.0},
    {"station": "CEDAR POINT 2", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 100.0},
    {"station": "CRYSLER", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 100.0},
    {"station": "GRANDSF", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 100.0},
    {"station": "KINGSTONSF", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 100.0},
    {"station": "EAST LAKE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "ERIEAU", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "GREENWICH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "NORTH KENT", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "PORT BURWELL", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "SPENCE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "ZURICH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 99.0},
    {"station": "CARIBOUFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 94.0},
    {"station": "SHANNON", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 91.0},
    {"station": "APIROQUOIS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 90.0},
    {"station": "BARRETT", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 89.0},
    {"station": "TILBURY BATTERY STORAGE", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 87.0},
    {"station": "NPKIRKLAND-G1-G5", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 82.0},
    {"station": "GARTSHORE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 81.0},
    {"station": "KIPLING 2", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 79.0},
    {"station": "HARMON 2", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 78.0},
    {"station": "DILLON", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 78.0},
    {"station": "RIPLEY SOUTH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 76.0},
    {"station": "LITTLELONG 2", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 75.0},
    {"station": "AMHERST ISLAND", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 74.0},
    {"station": "BORNISH", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 73.0},
    {"station": "LITTLELONG", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 72.0},
    {"station": "CAMERONFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 71.0},
    {"station": "TAOHSC", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 70.0},
    {"station": "DA WATSON", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 70.0},
    {"station": "WHITEDOG", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 68.0},
    {"station": "AUBREYFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 66.0},
    {"station": "MANITOUFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 66.0},
    {"station": "MACKAYGS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 62.0},
    {"station": "NORTHBAYGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 60.0},
    {"station": "ADELAIDE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 60.0},
    {"station": "BLAKE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 60.0},
    {"station": "MCLEANSMTNWF-LT.AG_T1", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 60.0},
    {"station": "ROMNEY", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 60.0},
    {"station": "TUNISGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 59.0},
    {"station": "ALEXANDER", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 57.0},
    {"station": "WHITBYCGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 55.0},
    {"station": "GOREWAY BESS", "fuel": "OTHER", "unit_count": 1, "nameplate_mw": 55.0},
    {"station": "STONE MILLS SF", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 54.0},
    {"station": "DPNTMTLND", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 52.0},
    {"station": "SILVERFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 51.0},
    {"station": "GOSFIELDWGS", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 51.0},
    {"station": "SOUTHGATE SF", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 50.0},
    {"station": "WINDSOR AIRPORT SF", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 50.0},
    {"station": "TBAYBOWATER CTS", "fuel": "BIOFUEL", "unit_count": 1, "nameplate_mw": 50.0},
    {"station": "AGUASABON", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 49.0},
    {"station": "PAROCHES", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 49.0},
    {"station": "GTAA", "fuel": "GAS", "unit_count": 3, "nameplate_mw": 47.0},
    {"station": "EAST WINDSOR-G1", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 46.0},
    {"station": "TAWINDSOR", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 46.0},
    {"station": "REDROCK", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 45.0},
    {"station": "NANTICOKE SOLAR", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 44.0},
    {"station": "RAYNER", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 42.0},
    {"station": "ARNPRIOR", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 41.0},
    {"station": "BOW LAKE 2", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 40.0},
    {"station": "GRAND VALLEY 3", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 40.0},
    {"station": "KINGSBRIDGE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 40.0},
    {"station": "LANDON", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 40.0},
    {"station": "NORTHLAND POWER SOLAR FACILITIES", "fuel": "SOLAR", "unit_count": 1, "nameplate_mw": 40.0},
    {"station": "DOWCHEMICAL", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 36.0},
    {"station": "CLERGUE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 33.0},
    {"station": "COCHRANECGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 32.0},
    {"station": "KAPGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 29.0},
    {"station": "DECEWND1", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 29.0},
    {"station": "PETER SUTHERLAND SR", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 27.0},
    {"station": "UMBATAFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 25.0},
    {"station": "GOULAIS", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 25.0},
    {"station": "NIPIGONGS", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 23.0},
    {"station": "EARFALLS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 22.0},
    {"station": "HOLINGSWTH", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 22.0},
    {"station": "LONGSAULTE", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 20.0},
    {"station": "BOW LAKE", "fuel": "WIND", "unit_count": 1, "nameplate_mw": 20.0},
    {"station": "CARMICHAEL", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 19.0},
    {"station": "NAGAGAMI", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 18.0},
    {"station": "ABKENORA", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 16.0},
    {"station": "MISSION", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 15.0},
    {"station": "STEEPHILL", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 15.0},
    {"station": "HARRIS", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 12.0},
    {"station": "FORTFRANCSWC", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 8.0},
    {"station": "LOWER WHITE RIVER", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 3.0},
    {"station": "UPPER WHITE RIVER", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 2.0},
    {"station": "NPKIRKLAND", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "ATIKOKAN", "fuel": "BIOFUEL", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "EAST WINDSOR-G2", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "GREENFIELD ENERGY CENTRE-G1", "fuel": "GAS", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "KAKABEKA", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "KIPLING", "fuel": "HYDRO", "unit_count": 1, "nameplate_mw": 0.0},
    {"station": "CALSTOCKGS", "fuel": "BIOFUEL", "unit_count": 1, "nameplate_mw": 0.0},
]

# Fuel-type rollup, computed at module load for convenience.
IESO_FUEL_MIX_MW: dict[str, float] = {}
for _s in IESO_GENERATORS:
    IESO_FUEL_MIX_MW[_s['fuel']] = IESO_FUEL_MIX_MW.get(_s['fuel'], 0.0) + _s['nameplate_mw']
