"""
Point-in-polygon territory check against the OEB Distributor Service
Territories dataset.

Replaces the previous 40 km substation-radius proxy in grid/generator.py
with a real boundary check: a candidate is "in Alectra's territory" iff
its (lat, lon) falls inside one of Alectra's official OEB franchise
polygons. Per REPORTS_COHESION.md §0, this trades a documented heuristic
for the real boundary the regulator publishes.

Polygon data lives in _oeb_territories_generated.py (auto-generated by
backend/scripts/ingest_oeb_territories.py from the OEB KMZ). This module
just provides the lookup + point-in-polygon math; rerun the ingest
script after an OEB dataset refresh.

The runtime cost of a single point-in-polygon check is O(V) for V
vertices in the named utility's MultiPolygon. Hydro One is the worst
case (~101k vertices) and runs in ~5 ms on a modern CPU. The bbox
short-circuit at the top of `point_in_territory` makes most rejections
constant-time. No external dependencies — stdlib only.
"""
from __future__ import annotations

from typing import Optional

from backend.services._oeb_territories_generated import TERRITORIES


# Map the lowercase utility keys used everywhere else in the pipeline
# (_UTILITY_TO_PROVINCE in grid_intelligence.py, SUBSTATIONS_BY_OPERATOR
# in _substations_generated.py) to the OEB's canonical legal names that
# key TERRITORIES. The OEB uses corporate names with "Inc." / "Limited"
# suffixes; our pipeline keys are short colloquial names.
#
# Entries here are derived from a one-time scan of the KML's <name> tags
# against the _UTILITY_TO_PROVINCE table. Keep this in sync when adding
# new entries to _UTILITY_TO_PROVINCE.
_KEY_TO_OEB_NAME: dict[str, str] = {
    "alectra": "Alectra Utilities Corporation",
    "toronto hydro": "Toronto Hydro-Electric System Limited",
    "hydro one": "Hydro One Networks Inc.",
    "hydro ottawa": "Hydro Ottawa Limited",
    "elexicon": "Elexicon Energy Inc.",
    "enova power": "Enova Power Corp.",
    "essex power": "Essex Powerlines Corporation",
    "festival hydro": "Festival Hydro Inc.",
    "halton hills hydro": "Halton Hills Hydro Inc.",
    "hydro hawkesbury": "Hydro Hawkesbury Inc.",
    "london hydro": "London Hydro Inc.",
    "milton hydro": "Milton Hydro Distribution Inc.",
    "newmarket-tay power": "Newmarket-Tay Power Distribution Ltd.",
    "niagara peninsula energy": "Niagara Peninsula Energy Inc.",
    "north bay hydro": "North Bay Hydro Distribution Limited",
    "oakville hydro": "Oakville Hydro Electricity Distribution Inc.",
    "oshawa power": "Oshawa PUC Networks Inc.",
    "peterborough distribution": "Peterborough Distribution Inc.",
    "synergy north": "Synergy North Corporation",
    "thunder bay hydro": "Synergy North Corporation",
    "utilities kingston": "Kingston Hydro Corporation",
    "waterloo north hydro": "Waterloo North Hydro Inc.",
    "welland hydro": "Welland Hydro-Electric System Corp.",
    "epcor": "EPCOR Electricity Distribution Ontario Inc.",
}


def _oeb_name_for(utility_key: str) -> Optional[str]:
    """Look up the OEB canonical name for a colloquial utility key, with a
    case-insensitive substring fallback against TERRITORIES keys so a new
    LDC added to _UTILITY_TO_PROVINCE works without a code change here."""
    if not utility_key:
        return None
    key = utility_key.strip().lower()
    if key in _KEY_TO_OEB_NAME:
        return _KEY_TO_OEB_NAME[key]
    # Substring fallback — first OEB name containing the key string.
    for oeb_name in TERRITORIES:
        if key in oeb_name.lower():
            return oeb_name
    return None


def _point_in_ring(lon: float, lat: float, ring: list[tuple[float, float]]) -> bool:
    """Standard ray-casting point-in-polygon. Ring is a list of (lon, lat)
    tuples; the polygon is assumed closed (first == last) or implicitly
    closed by the algorithm. Points exactly on an edge are treated as
    inside, which matches GIS convention for franchise-boundary lookups
    (a customer ON the boundary line is served by the utility on either
    side; the OEB resolves these case-by-case, so "inside" is the safer
    default here)."""
    n = len(ring)
    if n < 3:
        return False
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = ring[i]
        xj, yj = ring[j]
        # Standard half-open ray-cast. The `(yi > lat) != (yj > lat)` test
        # avoids double-counting vertices at the ray's latitude.
        intersects = ((yi > lat) != (yj > lat)) and (
            lon < (xj - xi) * (lat - yi) / (yj - yi + 1e-12) + xi
        )
        if intersects:
            inside = not inside
        j = i
    return inside


def point_in_territory(lat: float, lon: float, utility_key: str) -> bool:
    """True iff (lat, lon) falls inside any of the named utility's OEB
    franchise polygons. Returns False when the utility key isn't in the
    OEB dataset (e.g. a BC / AB utility named in the prompt — the caller
    should fall back to substation-proximity routing in that case)."""
    oeb_name = _oeb_name_for(utility_key)
    if oeb_name is None:
        return False
    entry = TERRITORIES.get(oeb_name)
    if entry is None:
        return False

    # Bbox short-circuit — most rejections are constant-time.
    min_lat, min_lon, max_lat, max_lon = entry["bbox"]
    if lat < min_lat or lat > max_lat or lon < min_lon or lon > max_lon:
        return False

    # Point-in-polygon for each MultiPolygon patch. Inside any outer ring
    # AND not inside any hole within that ring = inside the patch.
    for patch in entry["polygons"]:
        if not patch:
            continue
        outer = patch[0]
        if not _point_in_ring(lon, lat, outer):
            continue
        # In an outer ring — check holes.
        in_hole = False
        for hole in patch[1:]:
            if _point_in_ring(lon, lat, hole):
                in_hole = True
                break
        if not in_hole:
            return True
    return False


def has_polygon_for(utility_key: str) -> bool:
    """True iff the OEB dataset has polygons for the named utility. Used by
    the caller to decide whether to use polygon-based routing or fall
    back to the substation-proximity proxy."""
    return _oeb_name_for(utility_key) is not None
