// Static-fixture loader for demo mode.
//
// Vite's `import.meta.glob` statically resolves every JSON file in the
// fixtures directory at build time and code-splits them into the bundle.
// At runtime we look up by prefix and return the cached JSON. No network
// round-trip, no async deserialization — the data is just there.
//
// The fixtures themselves are generated by:
//
//     docker compose exec api python -m backend.scripts.export_demo_fixtures
//
// When no fixtures exist (first-time setup, before the script has been
// run), every loader function returns `null` and the demo intercept in
// `api/client.ts` falls through to the real backend call (which will
// 404 on Vercel, surfacing a clear error rather than blank silence).

import { DEMO_JOB_PREFIXES } from './jobs'
import type { PipelineId } from '../pipelines'
import type { JobListItem, JobStatus } from '../api/types'

interface FixtureFile {
  prefix: string
  pipeline_id: PipelineId
  job_list_item: JobListItem
  job_status: JobStatus
  // The `result` blob's shape is pipeline-specific (SitingPlan, ResiliencePlan,
  // ElectrificationPlan, InvestmentPlan, ExpansionPlan). The intercept layer
  // returns it as-is and lets the consuming hook cast.
  result: unknown
}

// import.meta.glob returns a map of relative-path → loader function.
// `eager: true` inlines the JSON synchronously at build time instead of
// returning a dynamic import — fine for our 5 small files, and lets us
// keep the lookup API synchronous.
const FIXTURE_MODULES = import.meta.glob<FixtureFile>('./fixtures/*.json', {
  eager: true,
  import: 'default',
})

// Index: prefix → FixtureFile. Built once at module load.
const FIXTURES_BY_PREFIX = new Map<string, FixtureFile>()
for (const path in FIXTURE_MODULES) {
  const fixture = FIXTURE_MODULES[path]
  if (fixture && fixture.prefix) {
    FIXTURES_BY_PREFIX.set(fixture.prefix, fixture)
  }
}

// Index: full job_id → FixtureFile. Built once at module load.
const FIXTURES_BY_JOB_ID = new Map<string, FixtureFile>()
for (const fixture of FIXTURES_BY_PREFIX.values()) {
  if (fixture.job_status?.job_id) {
    FIXTURES_BY_JOB_ID.set(fixture.job_status.job_id, fixture)
  }
}


export function hasFixtures(): boolean {
  return FIXTURES_BY_PREFIX.size > 0
}


export function fixtureCount(): number {
  return FIXTURES_BY_PREFIX.size
}


function findFixture(jobId: string): FixtureFile | null {
  // Exact full-UUID match wins.
  const exact = FIXTURES_BY_JOB_ID.get(jobId)
  if (exact) return exact
  // Otherwise try prefix match — supports callers that pass an 8-char prefix.
  for (const prefix of FIXTURES_BY_PREFIX.keys()) {
    if (jobId.startsWith(prefix)) {
      return FIXTURES_BY_PREFIX.get(prefix) ?? null
    }
  }
  return null
}


// ── Loader API ────────────────────────────────────────────────────────── //
//
// Each function mirrors a single `api.*` method's return shape so the
// intercept in `api/client.ts` can drop one in without any reshape work.

export function loadDemoJobStatus(jobId: string): JobStatus | null {
  return findFixture(jobId)?.job_status ?? null
}


export function loadDemoResults(jobId: string): unknown | null {
  return findFixture(jobId)?.result ?? null
}


export function loadDemoJobList(): JobListItem[] {
  // Only include fixtures whose pipeline_id is in the live DEMO_JOB_PREFIXES
  // config. This lets the operator quietly drop a fixture (by removing it
  // from the prefix list) without having to delete its JSON file.
  const activePrefixes = new Set(DEMO_JOB_PREFIXES.map((c) => c.prefix))
  const out: JobListItem[] = []
  for (const fixture of FIXTURES_BY_PREFIX.values()) {
    if (!activePrefixes.has(fixture.prefix)) continue
    out.push(fixture.job_list_item)
  }
  // Newest first, mirroring `crud.list_jobs` ordering.
  out.sort((a, b) => (b.created_at || '').localeCompare(a.created_at || ''))
  return out
}


// Reverse lookup: is this job_id served by a local fixture? Used by
// the intercept to decide between "load JSON" and "hit network".
export function isFixtureJobId(jobId: string | null | undefined): boolean {
  if (!jobId) return false
  return findFixture(jobId) !== null
}
