import { useRef } from 'react'
import { Link } from 'react-router-dom'
import { ScrollIndicator, useSmoothScroll } from '../components/SmoothStage'
import './LegalPage.css'

const LOGO = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" aria-hidden="true">
    <rect width="32" height="32" rx="7" fill="#1f1e1d"/>
    <g transform="translate(6.25, 3) scale(0.8125)">
      <path d="M12 0 C 12 8, 22 14, 22 22 A 10 10 0 1 1 2 22 C 2 14, 12 8, 12 0 Z" fill="#F38764"/>
    </g>
  </svg>
)

export function TermsPage() {
  const scrollRef = useRef<HTMLDivElement>(null)
  useSmoothScroll(scrollRef)
  return (
    <div ref={scrollRef} className="legal-root smooth-scroll">
      <header className="topbar">
        <span />
        <Link className="brand" to="/login" aria-label="Skorpio">
          {LOGO}
          <span className="wordmark">SKORPIO</span>
        </Link>
        <Link className="back" to="/login">← Back to sign in</Link>
      </header>

      <main className="content">
        <div className="eyebrow">Legal · Terms</div>
        <h1>Terms of Use</h1>
        <p className="meta">Effective date: May 16, 2025 · Last updated: May 16, 2025</p>

        <p>
          These Terms of Use ("<strong>Terms</strong>") govern your access to and use of the
          Skorpio Operator Console ("<strong>Skorpio</strong>," "<strong>Service</strong>")
          operated by the Skorpio team. Please read these Terms carefully before using the
          Service.
        </p>
        <p>
          By creating an account or otherwise accessing the Service you agree to be bound by
          these Terms. If you do not agree, do not use the Service.
        </p>

        <div className="section-divider" />

        <h2>1. Eligibility</h2>
        <p>You must be at least 18 years of age and have the authority to enter into these Terms
        on behalf of yourself or your organisation. If you are accepting on behalf of a company
        or other legal entity, you represent that you have the authority to bind that entity.</p>

        <h2>2. Description of Service</h2>
        <p>Skorpio is an AI-assisted grid-analysis console that provides datacenter siting
        recommendations, winter-peak stress testing, neighbourhood electrification scoring, grid
        investment prioritisation, and datacenter expansion planning for the Canadian electricity
        market. Outputs are generated by large language models and are provided for informational
        and planning purposes only.</p>

        <h2>3. Acceptable Use</h2>
        <p>You agree to use the Service only for lawful purposes and in a manner consistent with
        all applicable federal, provincial, and local laws and regulations. Specifically, you
        agree <strong>not</strong> to:</p>
        <ul>
          <li>Submit false, misleading, or deceptive inputs intended to generate erroneous reports
          that could harm third parties.</li>
          <li>Attempt to reverse-engineer, scrape, or extract the underlying models, data
          sources, or proprietary algorithms.</li>
          <li>Use automated systems (bots, scrapers, crawlers) to access the Service beyond what
          is explicitly permitted by the API.</li>
          <li>Share your account credentials or allow unauthorised parties to access the
          Service through your account.</li>
          <li>Interfere with or disrupt the integrity or performance of the Service or its
          underlying infrastructure.</li>
          <li>Use the Service to develop a competing product or service without our written
          consent.</li>
        </ul>

        <h2>4. AI-Generated Content and Limitations</h2>
        <p>Reports and recommendations produced by Skorpio are generated by AI models and are
        provided for <strong>informational purposes only</strong>. They do not constitute
        professional engineering advice, regulatory guidance, or investment recommendations.
        You are solely responsible for validating any outputs against applicable standards and
        for all decisions made on the basis of those outputs.</p>
        <p>AI-generated content may contain errors, omissions, or outdated information.
        Skorpio makes no warranty that outputs are accurate, complete, or fit for any
        particular purpose.</p>

        <h2>5. Intellectual Property</h2>
        <p>The Service, including its software, visual design, and proprietary data, is owned
        by Skorpio and its licensors and is protected by copyright, trade-secret, and other
        intellectual-property laws. You are granted a limited, non-exclusive, non-transferable
        licence to access and use the Service for its intended purpose.</p>
        <p>You retain ownership of the workload specifications and parameters you submit.
        By submitting them you grant Skorpio a licence to process them for the sole purpose
        of providing the Service and improving its quality.</p>

        <h2>6. Privacy</h2>
        <p>Your use of the Service is also governed by our <Link to="/privacy">Privacy
        Policy</Link>, which is incorporated into these Terms by reference.</p>

        <h2>7. Disclaimer of Warranties</h2>
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND,
        EXPRESS OR IMPLIED. SKORPIO DISCLAIMS ALL WARRANTIES INCLUDING, WITHOUT LIMITATION,
        IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE,
        OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

        <h2>8. Limitation of Liability</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SKORPIO AND ITS AFFILIATES,
        OFFICERS, EMPLOYEES, AGENTS, AND LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING LOSS OF PROFITS,
        DATA, GOODWILL, OR BUSINESS INTERRUPTION) ARISING FROM YOUR USE OF OR INABILITY TO
        USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

        <h2>9. Termination</h2>
        <p>We may suspend or terminate your access to the Service at any time, with or without
        cause or notice, if we believe you have violated these Terms or if required by law.
        Upon termination, the licences granted to you cease immediately. Sections 4–10 survive
        termination.</p>

        <h2>10. Changes to These Terms</h2>
        <p>We may modify these Terms at any time by posting the revised version on this page.
        Your continued use of the Service after changes are posted constitutes your acceptance
        of the revised Terms. If we make material changes we will make reasonable efforts to
        notify you (e.g., by email or an in-app notice).</p>

        <h2>11. Governing Law</h2>
        <p>These Terms are governed by the laws of the Province of Ontario and the federal laws
        of Canada applicable therein, without regard to conflict-of-law principles. Any dispute
        arising from these Terms or the Service shall be subject to the exclusive jurisdiction of
        the courts of Ontario.</p>

        <h2>12. Contact</h2>
        <p>If you have questions about these Terms, please contact the Skorpio team. We will
        respond within a reasonable timeframe.</p>
      </main>
      <ScrollIndicator targetRef={scrollRef} />
    </div>
  )
}
